pipeline {
    agent none
    stages {
        stage('Build Centos') {
            agent {
                dockerfile {
                    filename 'Centos-Dockerfile'
                    dir 'jenkins'
                }
            }
            steps {
                sh './bootstrap.sh && ./configure --prefix=$PWD/install --libdir=$PWD/install/lib -q --enable-debug CXXFLAGS=-coverage CFLAGS=-coverage LDFLAGS=-lgcov && make install && export LD_LIBRARY_PATH=$PWD/install/lib && export CPPFLAGS=-I$PWD/install/include && (cd pytrap && make coverage; python setup.py install;)'
            }
        }
        stage('Build Debian packages') {
            agent {
                dockerfile {
                    filename 'Debian-Dockerfile'
                    dir 'jenkins'
                }
            }
            steps {
               sh '( cd libtrap; ./bootstrap.sh && ./configure -q && make deb && dpkg -i ./libtrap*.deb;)'
               sh '( cd unirec; ./bootstrap.sh && ./configure -q && make deb && dpkg -i ./unirec*.deb;)'
               sh '( cd common; ./bootstrap.sh && ./configure -q && make deb && dpkg -i ./nemea-common*.deb;)'
            }
        }
    }



}
