pipeline {
    agent none
    stages {
        stage('Build Centos') {
            agent {
                dockerfile {
                    filename 'Centos-Dockerfile'
                    dir 'jenkins'
                }
            }
            steps {
                //sh './bootstrap.sh && ./configure --prefix=$PWD/install --libdir=$PWD/install/lib -q --enable-debug CXXFLAGS=-coverage CFLAGS=-coverage LDFLAGS=-lgcov && make rpm make install && export LD_LIBRARY_PATH=$PWD/install/lib && export CPPFLAGS=-I$PWD/install/include && (cd pytrap && make coverage; python setup.py install;)'

               sh '/usr/sbin/groupadd -f -g `id -g` jenkins; /usr/sbin/useradd jenkins -u `id -u` -g `id -g`; true'

               sh '( cd libtrap; ./bootstrap.sh && ./configure -q && make rpm && sudo yum install -y ./RPMBUILD/RPMS/*/libtrap*.rpm;)'
               sh '( cd unirec; ./bootstrap.sh && ./configure -q && make rpm && sudo yum install -y ./RPMBUILD/RPMS/*/unirec*.rpm;)'
               sh '( cd common; ./bootstrap.sh && ./configure -q && make rpm && sudo yum install -y ./RPMBUILD/RPMS/*/nemea-common*.rpm;)'
               sh 'mkdir rpms; find libtrap unirec common -name "*.rpm" -exec mv {} rpms ";"'
               archiveArtifacts artifacts: 'rpms/*', onlyIfSuccessful: true
            }
        }
        stage('Build Debian packages') {
            agent {
                dockerfile {
                    filename 'Debian-Dockerfile'
                    dir 'jenkins'
                }
            }
            steps {
               sh '/usr/sbin/groupadd -f -g `id -g` jenkins; /usr/sbin/useradd jenkins -u `id -u` -g `id -g`; true'

               sh '( cd libtrap; ./bootstrap.sh && ./configure -q && make deb && sudo dpkg -i ./libtrap*.deb;)'
               sh '( cd unirec; ./bootstrap.sh && ./configure -q && make deb && sudo dpkg -i ./unirec*.deb;)'
               sh '( cd common; ./bootstrap.sh && ./configure -q && make deb && sudo dpkg -i ./nemea-common*.deb;)'
               sh 'mkdir debs; find libtrap unirec common -name "*.deb" -exec mv {} debs ";"'
               archiveArtifacts artifacts: 'debs/*', onlyIfSuccessful: true
            }
        }
    }



}
